test

diff --git a/.github/workflows/npm-package-release.yml b/.github/workflows/npm-package-release.yml
--- a/.github/workflows/npm-package-release.yml
+++ b/.github/workflows/npm-package-release.yml
@@ -1,12 +1,13 @@
 name: NPM Packages Release
-on:
-  push:
-    branches:
-      - main
+on: [push]
+  
+  # push:
+  #   branches:
+  #     - main
 
 jobs:
   release:
-    if: ${{ github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'NPM Package Release') }}
+    # if: ${{ github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'NPM Package Release') }}
     runs-on: ubuntu-latest
     permissions:
       id-token: write
@@ -90,100 +91,100 @@ jobs:
       # from here on, we'll skip if OLD_HASH and NEW_HASH are the same (ie no publish)
       # this means we need to skip every step by using an if statement.
       # set npm version
-      - name: Set Version
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: |
-          npm version prerelease --preid alpha --no-git-tag-version -w @rainlanguage/ui-components -w @rainlanguage/orderbook
-          echo "NEW_VERSION=$(jq -r '.version' ./packages/orderbook/package.json)" >> $GITHUB_ENV
+      # - name: Set Version
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: |
+      #     npm version prerelease --preid alpha --no-git-tag-version -w @rainlanguage/ui-components -w @rainlanguage/orderbook
+      #     echo "NEW_VERSION=$(jq -r '.version' ./packages/orderbook/package.json)" >> $GITHUB_ENV
 
-      # sometimes the first or second try to update the version fails (npm bug?) so we retry max 5 times to
-      # make sure it updates the version successfully before proceeding and bail out if it failed to update
-      - name: Update orderbook Dependency Version for ui-components
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: |
-          set -e
-          current_version() {
-            jq -r '.dependencies."@rainlanguage/orderbook"' ./packages/ui-components/package.json
-          };
-          count=1;
-          while [[ $(current_version) != "${{ env.NEW_VERSION }}" && $count -le 5 ]]; do
-            echo "Trying to update orderbook dependency of ui-components pkg, attempt $count...";
-            ((count++));
-            npm install -w @rainlanguage/ui-components @rainlanguage/orderbook@=${{ env.NEW_VERSION }} --save-exact;
-            sleep 3;
-          done;
-          if [[ $(current_version) != "${{ env.NEW_VERSION }}" ]]; then
-            echo "Failed to update orderbook dependency version for ui-components after 5 attempts, aborting...";
-            exit 1;
-          else
-            echo "Successfully updated to $(current_version)";
-          fi;
+      # # sometimes the first or second try to update the version fails (npm bug?) so we retry max 5 times to
+      # # make sure it updates the version successfully before proceeding and bail out if it failed to update
+      # - name: Update orderbook Dependency Version for ui-components
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: |
+      #     set -e
+      #     current_version() {
+      #       jq -r '.dependencies."@rainlanguage/orderbook"' ./packages/ui-components/package.json
+      #     };
+      #     count=1;
+      #     while [[ $(current_version) != "${{ env.NEW_VERSION }}" && $count -le 5 ]]; do
+      #       echo "Trying to update orderbook dependency of ui-components pkg, attempt $count...";
+      #       ((count++));
+      #       npm install -w @rainlanguage/ui-components @rainlanguage/orderbook@=${{ env.NEW_VERSION }} --save-exact;
+      #       sleep 3;
+      #     done;
+      #     if [[ $(current_version) != "${{ env.NEW_VERSION }}" ]]; then
+      #       echo "Failed to update orderbook dependency version for ui-components after 5 attempts, aborting...";
+      #       exit 1;
+      #     else
+      #       echo "Successfully updated to $(current_version)";
+      #     fi;
 
-      # Commit changes and tag
-      - name: Commit And Tag
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: |
-          git add "packages/orderbook/package.json"
-          git add "packages/ui-components/package.json"
-          git add "package-lock.json"
-          git commit -m "NPM Package Release v${{ env.NEW_VERSION }}"
-          git tag npm-v${{ env.NEW_VERSION }}
+      # # Commit changes and tag
+      # - name: Commit And Tag
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: |
+      #     git add "packages/orderbook/package.json"
+      #     git add "packages/ui-components/package.json"
+      #     git add "package-lock.json"
+      #     git commit -m "NPM Package Release v${{ env.NEW_VERSION }}"
+      #     git tag npm-v${{ env.NEW_VERSION }}
 
-      # Push the commit to remote
-      - name: Push Changes To Remote
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: |
-          git push origin
-          git push -u origin npm-v${{ env.NEW_VERSION }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # # Push the commit to remote
+      # - name: Push Changes To Remote
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: |
+      #     git push origin
+      #     git push -u origin npm-v${{ env.NEW_VERSION }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # Create orderbook npm package tarball
-      - name: Create orderbook NPM Package Tarball
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: echo "NPM_PACKAGE=$(npm pack --silent -w @rainlanguage/orderbook)" >> $GITHUB_ENV
+      # # Create orderbook npm package tarball
+      # - name: Create orderbook NPM Package Tarball
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: echo "NPM_PACKAGE=$(npm pack --silent -w @rainlanguage/orderbook)" >> $GITHUB_ENV
 
-      - name: Rename orderbook NPM Package Tarball
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: mv ${{ env.NPM_PACKAGE }} orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
+      # - name: Rename orderbook NPM Package Tarball
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: mv ${{ env.NPM_PACKAGE }} orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
 
-      # publish orderbook pkg to npm
-      - name: Publish orderbook pkg To NPM
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        uses: JS-DevTools/npm-publish@v3
-        with:
-          token: ${{ secrets.NPM_TOKEN }}
-          access: public
-          package: orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
+      # # publish orderbook pkg to npm
+      # - name: Publish orderbook pkg To NPM
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   uses: JS-DevTools/npm-publish@v3
+      #   with:
+      #     token: ${{ secrets.NPM_TOKEN }}
+      #     access: public
+      #     package: orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
 
-      # Create npm package tarball for ui-components
-      - name: Create ui-components NPM Package Tarball
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: echo "NPM_PACKAGE=$(npm pack --silent -w @rainlanguage/ui-components)" >> $GITHUB_ENV
+      # # Create npm package tarball for ui-components
+      # - name: Create ui-components NPM Package Tarball
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: echo "NPM_PACKAGE=$(npm pack --silent -w @rainlanguage/ui-components)" >> $GITHUB_ENV
 
-      - name: Rename ui-components NPM Package Tarball
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        run: mv ${{ env.NPM_PACKAGE }} ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
+      # - name: Rename ui-components NPM Package Tarball
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   run: mv ${{ env.NPM_PACKAGE }} ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
 
-      # publish ui-components to npm
-      - name: Publish ui-components To NPM
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        uses: JS-DevTools/npm-publish@v3
-        with:
-          token: ${{ secrets.NPM_TOKEN }}
-          access: public
-          package: ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
+      # # publish ui-components to npm
+      # - name: Publish ui-components To NPM
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   uses: JS-DevTools/npm-publish@v3
+      #   with:
+      #     token: ${{ secrets.NPM_TOKEN }}
+      #     access: public
+      #     package: ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
 
-      # Create gitHub release with tarballs
-      - name: Create GitHub Release with orderbook pkg
-        if: ${{ env.OLD_HASH != env.NEW_HASH }}
-        id: gh_release
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: npm-v${{ env.NEW_VERSION }}
-          name: NPM Package Release v${{ env.NEW_VERSION }}
-          files: |
-            orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
-            ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # # Create gitHub release with tarballs
+      # - name: Create GitHub Release with orderbook pkg
+      #   if: ${{ env.OLD_HASH != env.NEW_HASH }}
+      #   id: gh_release
+      #   uses: softprops/action-gh-release@v2
+      #   with:
+      #     tag_name: npm-v${{ env.NEW_VERSION }}
+      #     name: NPM Package Release v${{ env.NEW_VERSION }}
+      #     files: |
+      #       orderbook_npm_package_${{ env.NEW_VERSION }}.tgz
+      #       ui_components_npm_package_${{ env.NEW_VERSION }}.tgz
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
