Update npm-package-release.yml

diff --git a/.github/workflows/npm-package-release.yml b/.github/workflows/npm-package-release.yml
--- a/.github/workflows/npm-package-release.yml
+++ b/.github/workflows/npm-package-release.yml
@@ -74,23 +74,26 @@ jobs:
           npm version prerelease --preid alpha --no-git-tag-version -w @rainlanguage/ui-components -w @rainlanguage/orderbook
           echo "NEW_VERSION=$(jq -r '.version' ./packages/orderbook/package.json)" >> $GITHUB_ENV
 
-      # sometimes the first or second try to update the version fails (npm bug?) so we retry max 5 times
-      # to make sure it updates the version successfuly before proceeding and bail out if it failed to update
+      # sometimes the first or second try to update the version fails (npm bug?) so we retry max 5 times to
+      # make sure it updates the version successfully before proceeding and bail out if it failed to update
       - name: Update orderbook Dependency Version for ui-components
         run: |
+          set -e
           current_version() {
             jq -r '.dependencies."@rainlanguage/orderbook"' ./packages/ui-components/package.json
           };
           count=1;
           while [[ $(current_version) != "${{ env.NEW_VERSION }}" && $count -le 5 ]]; do
-            echo "Trying to update orderbook dependency of ui-components pkg, count $count...";
+            echo "Trying to update orderbook dependency of ui-components pkg, attempt $count...";
             ((count++));
             npm install -w @rainlanguage/ui-components @rainlanguage/orderbook@=${{ env.NEW_VERSION }} --save-exact;
             sleep 3;
           done;
           if [[ $(current_version) != "${{ env.NEW_VERSION }}" ]]; then
-            echo "Failed to update orderbook dependency version for ui-components, aborting...";
+            echo "Failed to update orderbook dependency version for ui-components after 5 attempts, aborting...";
             exit 1;
+          else
+            echo "Successfully updated to $(current_version)";
           fi;
 
       # Commit changes and tag
